2014-03-30 15:28:30 Warning: Warning (2): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in [D:\xampp\htdocs\PixlPost\lib\Cake\Model\Datasource\Database\Mysql.php, line 175]
Trace:
PDO::__construct() - [internal], line ??
Mysql::connect() - CORE\Cake\Model\Datasource\Database\Mysql.php, line 175
DboSource::__construct() - CORE\Cake\Model\Datasource\DboSource.php, line 260
ConnectionManager::getDataSource() - CORE\Cake\Model\ConnectionManager.php, line 105
AppController::beforeFilter() - APP\Controller\AppController.php, line 174
PagesController::beforeFilter() - APP\Controller\PagesController.php, line 37
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE\Cake\Event\CakeEventManager.php, line 247
Controller::startupProcess() - CORE\Cake\Controller\Controller.php, line 674
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 182
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 160
[main] - APP\webroot\index.php, line 92

2014-03-30 15:30:09 Error: [MissingTableException] Table media_articles for model MediaArticle was not found in datasource default.
Exception Attributes: array (
  'table' => 'media_articles',
  'class' => 'MediaArticle',
  'ds' => 'default',
)
Request URL: /PixlPost/article/8/monotone-celebrates-new-future-print-apprenticeships
Stack Trace:
#0 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(3498): Model->setSource('media_articles')
#1 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(864): Model->schema()
#3 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(892): Model->__isset('MediaArticle')
#4 D:\xampp\htdocs\PixlPost\app\Model\Article.php(786): Model->__get('MediaArticle')
#5 D:\xampp\htdocs\PixlPost\app\Model\Article.php(770): Article->getMedia('8', '/PixlPost/')
#6 D:\xampp\htdocs\PixlPost\app\Controller\ArticlesController.php(597): Article->viewArticle(Object(CakeRequest))
#7 [internal function]: ArticlesController->view()
#8 D:\xampp\htdocs\PixlPost\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ArticlesController), Array)
#9 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ArticlesController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\PixlPost\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-03-30 15:30:09 Warning: Warning (2): filemtime() [<a href='http://php.net/function.filemtime'>function.filemtime</a>]: stat failed for view in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 136]
Trace:
filemtime - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 136
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

2014-03-30 15:30:09 Warning: Warning (2): file_get_contents(view) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 153]
Trace:
file_get_contents - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 153
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

2014-03-30 15:30:21 Error: [MissingTableException] Table media_articles for model MediaArticle was not found in datasource default.
Exception Attributes: array (
  'table' => 'media_articles',
  'class' => 'MediaArticle',
  'ds' => 'default',
)
Request URL: /PixlPost/article/8/monotone-celebrates-new-future-print-apprenticeships
Stack Trace:
#0 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(3498): Model->setSource('media_articles')
#1 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(864): Model->schema()
#3 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(892): Model->__isset('MediaArticle')
#4 D:\xampp\htdocs\PixlPost\app\Model\Article.php(786): Model->__get('MediaArticle')
#5 D:\xampp\htdocs\PixlPost\app\Model\Article.php(770): Article->getMedia('8', '/PixlPost/')
#6 D:\xampp\htdocs\PixlPost\app\Controller\ArticlesController.php(597): Article->viewArticle(Object(CakeRequest))
#7 [internal function]: ArticlesController->view()
#8 D:\xampp\htdocs\PixlPost\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ArticlesController), Array)
#9 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ArticlesController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\PixlPost\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-03-30 15:30:21 Warning: Warning (2): filemtime() [<a href='http://php.net/function.filemtime'>function.filemtime</a>]: stat failed for view in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 136]
Trace:
filemtime - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 136
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

2014-03-30 15:30:21 Warning: Warning (2): file_get_contents(view) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 153]
Trace:
file_get_contents - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 153
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

2014-03-30 15:30:29 Error: [MissingTableException] Table media_articles for model MediaArticle was not found in datasource default.
Exception Attributes: array (
  'table' => 'media_articles',
  'class' => 'MediaArticle',
  'ds' => 'default',
)
Request URL: /PixlPost/article/1/welcome-to-adaptcms-3-0-1
Stack Trace:
#0 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(3498): Model->setSource('media_articles')
#1 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(864): Model->schema()
#3 D:\xampp\htdocs\PixlPost\lib\Cake\Model\Model.php(892): Model->__isset('MediaArticle')
#4 D:\xampp\htdocs\PixlPost\app\Model\Article.php(786): Model->__get('MediaArticle')
#5 D:\xampp\htdocs\PixlPost\app\Model\Article.php(770): Article->getMedia('1', '/PixlPost/')
#6 D:\xampp\htdocs\PixlPost\app\Controller\ArticlesController.php(597): Article->viewArticle(Object(CakeRequest))
#7 [internal function]: ArticlesController->view()
#8 D:\xampp\htdocs\PixlPost\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ArticlesController), Array)
#9 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\PixlPost\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ArticlesController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\PixlPost\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-03-30 15:30:29 Warning: Warning (2): filemtime() [<a href='http://php.net/function.filemtime'>function.filemtime</a>]: stat failed for view in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 136]
Trace:
filemtime - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 136
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

2014-03-30 15:30:29 Warning: Warning (2): file_get_contents(view) [<a href='http://php.net/function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in [D:\xampp\htdocs\PixlPost\app\View\AdaptcmsView.php, line 153]
Trace:
file_get_contents - [internal], line ??
AdaptcmsView::_evaluate() - APP\View\AdaptcmsView.php, line 153
View::_render() - CORE\Cake\View\View.php, line 897
AdaptcmsView::render() - APP\View\AdaptcmsView.php, line 116
Controller::render() - CORE\Cake\Controller\Controller.php, line 952
ExceptionRenderer::_outputMessage() - CORE\Cake\Error\ExceptionRenderer.php, line 273
ExceptionRenderer::error500() - CORE\Cake\Error\ExceptionRenderer.php, line 242
ExceptionRenderer::render() - CORE\Cake\Error\ExceptionRenderer.php, line 175
ErrorHandler::handleException() - CORE\Cake\Error\ErrorHandler.php, line 120
[main] - [internal], line ??

